#!/usr/bin/env bash

echo -e "    ==> updating cache ..."
sleep .5
awk '{printf("%c[2K", 27);printf("%s\r", $0)}' <(sudo apt-get update -y)
echo -e "    ==> running dist-upgrade ..."
sleep .5
awk '{printf("%c[2K", 27);printf("%s\r", $0)}' <(sudo apt-get dist-upgrade -y)
echo -e "    ==> removing unnecessary packages..."
sleep .5
awk '{printf("%c[2K", 27);printf("%s\r", $0)}' <(sudo apt-get autoremove -y)
echo -e "    ==> cleaningup ..."
sleep .5
awk '{printf("%c[2K", 27);printf("%s\r", $0)}' <(sudo apt-get autoclean -y)

