#!/usr/bin/env bash

function _runner() {
  _COLOR='\033[1;92m'
  _IGN_COLOR='\033[1;90m'
  _NC='\033[0m'
  echo -e "${_COLOR}    ----> ${1} ...${_NC}${_IGN_COLOR}"
  awk '{printf("%c[2K", 27);printf("%s\r", $0)}' <(${1})
  unset _COLOR _IGN_COLOR _NC
}

_runner 'brew update -v'
_runner 'brew upgrade -v'
_runner 'brew cleanup -s'
_runner 'brew cask outdated'
_runner 'brew cask upgrade'
_runner 'brew doctor'

